console.log(Number.MAX_SAFE_INTEGER);
console.log(Number.MAX_SAFE_INTEGER + 1);
console.log(Number.MAX_SAFE_INTEGER + 2);
console.log(Number.MAX_SAFE_INTEGER + 3);
console.log(Number.MAX_SAFE_INTEGER + 4);
console.log(Number.MAX_SAFE_INTEGER + 5);
console.log(Number.MAX_SAFE_INTEGER + 6);
console.log("-------------------------");
console.log(BigInt(Number.MAX_SAFE_INTEGER));
console.log(BigInt(Number.MAX_SAFE_INTEGER) + BigInt(1));
console.log(BigInt(Number.MAX_SAFE_INTEGER) + 2n);
console.log(BigInt(Number.MAX_SAFE_INTEGER) + 3n);
console.log(BigInt(Number.MAX_SAFE_INTEGER) + 4n);
console.log(BigInt(Number.MAX_SAFE_INTEGER) + 5n);
console.log(BigInt(Number.MAX_SAFE_INTEGER) + 6n);